### ISSUE TITLE
Server setting related errors are reported for the Python file

### ISSUE THREAD

**Issue by MichaReiser** [astral-sh/ty#613]
I've a `main.py` with an unresolved reference error and an error in my pyproject.toml

The server groups the pyproject.error under the `main.py`

`pyproject.toml`:

```toml
[project]
name = "micha-test"

[tool.ty.src]
exclude = ["***"]

```

`main.py`:

```py
def foo(a: str | None, b):
	if a is not None:
	   print(a)

unresolved

```

<img width="942" alt="Image" src="https://github.com/user-attachments/assets/59b2e9c5-eeea-4fdb-a772-1ac2b66924cb" />
