### ISSUE TITLE
Support for `executionEnvironments` in monorepos

### ISSUE THREAD

**Issue by tim-x-y-z** [astral-sh/ty#693]
Hi team,

First of all, thank you for the excellent work on `ty`!

In our monorepo setup, we rely on `executionEnvironments` in `pyrightconfig.toml` to isolate type checking per service and control `extraPaths` in a scoped, declarative way. Here's a simplified version of our config:

```toml
[tool.pyright]
include = ["."]
extraPaths = ["shared/lib"]
executionEnvironments = [
  { root = "service-a", extraPaths = ["service-a/src", "shared/lib"] },
  { root = "service-b", extraPaths = ["service-b/src", "shared/lib"] },
  { root = "frontend", extraPaths = ["frontend/src", "service-a/src", "shared/lib"] }
]
```
This pattern makes it easy to work in a monorepo with multiple isolated services while keeping path resolution clean and explicit.
It would be incredibly helpful if `ty` supported something similar!
